2022-01-03 01:03:49,884 INFO    MainThread:11208 [internal.py:wandb_internal():87] W&B internal server running at pid: 11208, started at: 2022-01-03 01:03:49.884071
2022-01-03 01:03:49,884 INFO    WriterThread:11208 [datastore.py:open_for_write():77] open: G:\thesis\aerial-imagery-segmentation-master\aerial-imagery-segmentation-master\dd-ml-segmentation-benchmark\wandb\run-20220103_010348-3ksvn21u\run-3ksvn21u.wandb
2022-01-03 01:03:49,884 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: check_version
2022-01-03 01:03:49,899 DEBUG   SenderThread:11208 [sender.py:send():234] send: header
2022-01-03 01:03:49,899 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: check_version
2022-01-03 01:03:52,227 DEBUG   SenderThread:11208 [sender.py:send():234] send: run
2022-01-03 01:03:52,290 DEBUG   SenderThread:11208 [git.py:repo():33] git repository is invalid
2022-01-03 01:03:54,946 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: run_start
2022-01-03 01:03:55,008 INFO    SenderThread:11208 [dir_watcher.py:__init__():169] watching files in: G:\thesis\aerial-imagery-segmentation-master\aerial-imagery-segmentation-master\dd-ml-segmentation-benchmark\wandb\run-20220103_010348-3ksvn21u\files
2022-01-03 01:03:55,008 INFO    SenderThread:11208 [sender.py:_start_run_threads():804] run started: 3ksvn21u with start time 1641153828
2022-01-03 01:03:55,008 DEBUG   SenderThread:11208 [sender.py:send():234] send: summary
2022-01-03 01:03:55,008 INFO    SenderThread:11208 [sender.py:_save_file():939] saving file wandb-summary.json with policy end
2022-01-03 01:03:55,039 DEBUG   HandlerThread:11208 [meta.py:__init__():40] meta init
2022-01-03 01:03:55,039 DEBUG   HandlerThread:11208 [meta.py:__init__():54] meta init done
2022-01-03 01:03:55,055 DEBUG   HandlerThread:11208 [meta.py:probe():214] probe
2022-01-03 01:03:55,055 DEBUG   HandlerThread:11208 [git.py:repo():33] git repository is invalid
2022-01-03 01:03:55,055 DEBUG   HandlerThread:11208 [meta.py:_save_pip():58] save pip
2022-01-03 01:03:55,055 DEBUG   HandlerThread:11208 [meta.py:_save_pip():72] save pip done
2022-01-03 01:03:55,055 DEBUG   HandlerThread:11208 [meta.py:_save_conda():79] save conda
2022-01-03 01:03:56,024 INFO    Thread-12 :11208 [dir_watcher.py:_on_file_created():217] file/dir created: G:\thesis\aerial-imagery-segmentation-master\aerial-imagery-segmentation-master\dd-ml-segmentation-benchmark\wandb\run-20220103_010348-3ksvn21u\files\conda-environment.yaml
2022-01-03 01:03:56,024 INFO    Thread-12 :11208 [dir_watcher.py:_on_file_created():217] file/dir created: G:\thesis\aerial-imagery-segmentation-master\aerial-imagery-segmentation-master\dd-ml-segmentation-benchmark\wandb\run-20220103_010348-3ksvn21u\files\wandb-summary.json
2022-01-03 01:03:56,024 INFO    Thread-12 :11208 [dir_watcher.py:_on_file_created():217] file/dir created: G:\thesis\aerial-imagery-segmentation-master\aerial-imagery-segmentation-master\dd-ml-segmentation-benchmark\wandb\run-20220103_010348-3ksvn21u\files\requirements.txt
2022-01-03 01:03:59,367 DEBUG   HandlerThread:11208 [meta.py:_save_conda():89] save conda done
2022-01-03 01:03:59,367 DEBUG   HandlerThread:11208 [meta.py:probe():252] probe done
2022-01-03 01:03:59,524 DEBUG   SenderThread:11208 [sender.py:send():234] send: files
2022-01-03 01:03:59,524 INFO    SenderThread:11208 [sender.py:_save_file():939] saving file wandb-metadata.json with policy now
2022-01-03 01:03:59,524 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:03:59,524 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:04:00,070 INFO    Thread-12 :11208 [dir_watcher.py:_on_file_modified():230] file/dir modified: G:\thesis\aerial-imagery-segmentation-master\aerial-imagery-segmentation-master\dd-ml-segmentation-benchmark\wandb\run-20220103_010348-3ksvn21u\files\conda-environment.yaml
2022-01-03 01:04:00,070 INFO    Thread-12 :11208 [dir_watcher.py:_on_file_created():217] file/dir created: G:\thesis\aerial-imagery-segmentation-master\aerial-imagery-segmentation-master\dd-ml-segmentation-benchmark\wandb\run-20220103_010348-3ksvn21u\files\wandb-metadata.json
2022-01-03 01:04:00,070 INFO    Thread-12 :11208 [dir_watcher.py:_on_file_created():217] file/dir created: G:\thesis\aerial-imagery-segmentation-master\aerial-imagery-segmentation-master\dd-ml-segmentation-benchmark\wandb\run-20220103_010348-3ksvn21u\files\output.log
2022-01-03 01:04:00,836 DEBUG   SenderThread:11208 [sender.py:send():234] send: config
2022-01-03 01:04:02,101 INFO    Thread-12 :11208 [dir_watcher.py:_on_file_modified():230] file/dir modified: G:\thesis\aerial-imagery-segmentation-master\aerial-imagery-segmentation-master\dd-ml-segmentation-benchmark\wandb\run-20220103_010348-3ksvn21u\files\output.log
2022-01-03 01:04:13,805 INFO    Thread-15 :11208 [upload_job.py:push():137] Uploaded file C:\Users\Shahyar\AppData\Local\Temp\tmp9sbsn4x_wandb\1d2iuzby-wandb-metadata.json
2022-01-03 01:04:15,852 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:04:15,852 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:04:23,398 INFO    Thread-12 :11208 [dir_watcher.py:_on_file_modified():230] file/dir modified: G:\thesis\aerial-imagery-segmentation-master\aerial-imagery-segmentation-master\dd-ml-segmentation-benchmark\wandb\run-20220103_010348-3ksvn21u\files\config.yaml
2022-01-03 01:04:25,773 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:04:32,444 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:04:32,444 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:04:48,756 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:04:48,756 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:04:58,734 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:05:05,610 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:05:05,610 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:05:25,640 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:05:25,640 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:05:32,123 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:05:43,373 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:05:43,373 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:08:19,923 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:08:23,767 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:08:32,188 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:08:51,951 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:08:54,779 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:08:55,888 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:08:55,888 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:09:11,981 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:09:11,981 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:09:20,916 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:09:28,060 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:09:28,060 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:09:48,062 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:09:48,062 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:10:02,624 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:10:08,061 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:10:08,061 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:10:23,181 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:10:27,279 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:10:27,279 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:10:43,578 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:10:43,578 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:10:56,563 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:11:03,594 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:11:03,594 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:11:19,782 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:11:19,782 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:11:29,003 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:11:37,096 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:11:37,096 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:11:54,798 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:11:54,798 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:12:01,907 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:12:14,154 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:12:14,154 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:12:30,292 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:12:30,292 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:12:34,805 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:12:46,372 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:12:46,372 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:13:03,073 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:13:03,073 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:13:07,807 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:13:19,240 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:13:19,240 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:13:35,506 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:13:35,506 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:13:41,974 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:13:52,444 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:13:52,444 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:14:11,206 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:14:11,206 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:14:17,138 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:14:28,125 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:14:28,125 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:14:44,546 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:14:44,547 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:14:48,474 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:15:01,302 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:15:01,302 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:15:18,607 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:15:18,607 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:15:19,810 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:15:34,811 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:15:34,811 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:15:51,031 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:15:51,031 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:15:52,109 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:16:07,127 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:16:07,127 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:16:23,614 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:16:23,615 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:16:25,133 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:16:40,140 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:16:40,140 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:16:56,255 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:16:56,255 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:16:57,904 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:17:12,324 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:17:12,324 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:17:28,395 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:17:28,395 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:17:29,598 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:17:44,600 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:17:44,600 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:18:00,059 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:18:00,682 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:18:00,683 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:18:16,771 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:18:16,772 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:18:30,374 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:18:32,841 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:18:32,841 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:18:48,900 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:18:48,900 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:19:00,797 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:19:04,984 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:19:04,984 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:19:21,055 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:19:21,055 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:19:32,259 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:19:37,473 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:19:37,473 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:19:53,587 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:19:53,587 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:20:04,376 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:20:09,679 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:20:09,679 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:20:29,695 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:20:29,695 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:20:49,722 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:20:56,720 ERROR   SenderThread:11208 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002849F9CC7F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002849F9CC7F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\wandb\sdk\internal\internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\wandb\vendor\gql-0.2.0\gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002849F9CC7F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-01-03 01:21:12,319 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:21:12,085 WARNING FileStreamThread:11208 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)). func: <bound method Session.post of <requests.sessions.Session object at 0x000002849F947610>>, args: ('https://api.wandb.ai/files/shahryar/uncategorized/3ksvn21u/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-03 01:21:28,768 WARNING FileStreamThread:11208 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/shahryar/uncategorized/3ksvn21u/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002849F9CC820>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002849F947610>>, args: ('https://api.wandb.ai/files/shahryar/uncategorized/3ksvn21u/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-03 01:21:29,768 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:21:44,187 WARNING FileStreamThread:11208 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/shahryar/uncategorized/3ksvn21u/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002849F9CC790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002849F947610>>, args: ('https://api.wandb.ai/files/shahryar/uncategorized/3ksvn21u/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-03 01:21:50,203 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:22:09,900 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:22:17,210 WARNING FileStreamThread:11208 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/shahryar/uncategorized/3ksvn21u/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002849F9CCF40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002849F947610>>, args: ('https://api.wandb.ai/files/shahryar/uncategorized/3ksvn21u/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-03 01:22:25,553 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:22:25,553 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:22:26,693 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:22:27,787 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:22:27,787 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:22:28,834 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:22:29,912 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:22:30,271 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:22:30,271 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:22:31,334 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:22:35,932 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:22:48,096 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:22:48,096 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:23:04,189 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:23:04,189 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:23:24,216 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:23:28,352 WARNING FileStreamThread:11208 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/shahryar/uncategorized/3ksvn21u/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002849F97AE50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002849F947610>>, args: ('https://api.wandb.ai/files/shahryar/uncategorized/3ksvn21u/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-03 01:23:44,239 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:24:43,845 WARNING FileStreamThread:11208 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/shahryar/uncategorized/3ksvn21u/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002849F9785B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002849F947610>>, args: ('https://api.wandb.ai/files/shahryar/uncategorized/3ksvn21u/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-03 01:25:11,125 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:25:22,453 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:25:33,546 WARNING FileStreamThread:11208 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/shahryar/uncategorized/3ksvn21u/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))). func: <bound method Session.post of <requests.sessions.Session object at 0x000002849F947610>>, args: ('https://api.wandb.ai/files/shahryar/uncategorized/3ksvn21u/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-03 01:25:33,812 ERROR   SenderThread:11208 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\wandb\sdk\internal\internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\wandb\vendor\gql-0.2.0\gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\fastai_gpu\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
2022-01-03 01:25:42,483 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:25:57,836 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:25:57,836 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:25:58,617 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:25:58,617 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:25:58,961 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:25:59,289 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:25:59,617 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:25:59,617 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:26:02,492 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:26:02,492 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:26:17,835 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:26:17,835 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:26:22,436 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:26:33,385 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:26:33,385 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:26:50,161 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:26:50,161 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:26:55,450 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:27:05,621 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:27:05,621 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:27:21,143 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:27:21,143 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:27:28,446 DEBUG   SenderThread:11208 [sender.py:send():234] send: stats
2022-01-03 01:27:36,534 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:27:36,534 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:27:52,460 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:27:52,460 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:28:08,169 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:28:08,169 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:28:28,183 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:28:28,184 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
2022-01-03 01:28:48,195 DEBUG   HandlerThread:11208 [handler.py:handle_request():130] handle_request: stop_status
2022-01-03 01:28:48,195 DEBUG   SenderThread:11208 [sender.py:send_request():248] send_request: stop_status
